<?php
$z[0]=Array("arcurl","",74,89);
$z[1]=Array("title","",98,112);
$z[2]=Array("picname","",127,143);
$z[3]=Array("title","",161,175);
$z[4]=Array("arcurl","",204,219);
$z[5]=Array("typelink","",228,245);
$z[6]=Array("typelink","",256,273);
$z[7]=Array("arcurl","",299,314);
$z[8]=Array("title","",323,337);
$z[9]=Array("title","",348,362);
$z[10]=Array("arcurl","",391,406);
$z[11]=Array("title","",415,429);

?>