<li class="shadow">
    <div class="hot c新品"></div>
	
    <a href="[field:arcurl/]" title="[field:title/]">
	<img src="[field:picname/]" border="0" alt="[field:title/]" />
	</a>
    <i><a href="[field:arcurl/]" title="[field:typelink/]" style="">[field:typelink/]</a></i>
    <b><a href="[field:arcurl/]" title="[field:title/]" style="">[field:title/]</a></b>
    <span><a href="[field:arcurl/]" title="[field:title/]" style="color:#fff;">产品详细</a></span>
	
    <p></p>
	</li>