<?php
$z[0]=Array("global","",155,187);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("channelartlist"," <SPAN class=ch><b><a href=\"{dede:field name='typeurl'/}\" title=\"{dede:field name='typename'/}\">{dede:field name='typename'/}</a></b>\r\n          <UL class=navsub>\r\n            {dede:channel type='sun' row='100'}\r\n            <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n            {/dede:channel}\r\n          </UL>\r\n          </SPAN> ",330,737);
$z[1][4]['typeid']="top";
$z[2]=Array("global","",764,796);
$z[2][4]['name']="cfg_templets_skin";

?>